apps:
  # --- NON environment ---
  - name: secret-store-non
    namespace: dotablaze-tech-non
    chartPath: charts/secret-store
    syncWave: "0"
    valueFiles:
      - values.yaml
      - values-non.yaml

  - name: meowbot-non
    namespace: dotablaze-tech-non
    chartPath: charts/meowbot
    syncWave: "1"
    valueFiles:
      - values.yaml
      - values-non.yaml
