replicaCount: 1

revisionHistoryLimit: 2

image:
  repository: dotablaze/meowbot
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""

fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ss-clusterissuer
  hosts:
    - host: meowbot.default.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - meowbot.default.jdwkube.com
      secretName: meowbot-default-tls

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"
  limits:
    memory: "64Mi"
    cpu: "50m"

livenessProbe:
  httpGet:
    path: /liveness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readiness
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

externalSecrets:
  - refreshInterval: 1m
    secretStoreName: k8s-secret-store
    secretName: meowbot-pg-default
  - refreshInterval: 1m
    secretStoreName: vault-secret-store
    secretName: meowbot-default

envs:
  MODE: dev
  DEBUG: true
  API_PORT: 8080
  WHITELISTED_GUILDS: ""
  DATABASE_URL: jdbc:postgresql://postgresql-cluster-non-rw.database:5432/dbtech_dev
  DATABASE_HOST: postgresql-cluster-non-rw.database
  DATABASE_PORT: 5432
  DATABASE_NAME: dbtech_dev

envSecrets:
  - secretKey: DATABASE_USER
    key: postgresql-cluster-non-app
    property: username
    secretName: meowbot-pg-default
  - secretKey: DATABASE_PASSWORD
    key: postgresql-cluster-non-app
    property: password
    secretName: meowbot-pg-default
  - secretKey: DISCORD_BOT_TOKEN
    key: dotablaze-tech-discord-bot-token
    property: token
    secretName: meowbot-default
