image:
  tag: ""

ingress:
  hosts:
    - host: meowbot.non.jdwlabs.com

externalSecrets:
  - refreshInterval: 1m
    secretStoreName: k8s-secret-store
    secretName: meowbot-pg-non
  - refreshInterval: 1m
    secretStoreName: vault
    secretName: meowbot-non

envs:
  MODE: non
  DEBUG: false
  DATABASE_URL: jdbc:postgresql://platform-postgresql-cluster-non-rw.database:5432/dotablazetech_non
  DATABASE_HOST: platform-postgresql-cluster-non-rw.database
  DATABASE_PORT: 5432
  DATABASE_NAME: dotablazetech_non

envSecrets:
  - secretKey: DATABASE_USER
    key: platform-postgresql-cluster-non-app
    property: username
    secretName: meowbot-pg-non
  - secretKey: DATABASE_PASSWORD
    key: platform-postgresql-cluster-non-app
    property: password
    secretName: meowbot-pg-non
  - secretKey: DISCORD_BOT_TOKEN
    key: dotablaze-tech-discord-bot-token
    property: token
    secretName: meowbot-non
